# Generated by Django 3.2.12 on 2022-08-16 10:33

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IpifRepo',
            fields=[
                ('endpoint_slug', models.CharField(db_index=True, default=None, editable=False, max_length=20, primary_key=True, serialize=False)),
                ('endpoint_name', models.CharField(default='', max_length=30)),
                ('endpoint_uri', models.URLField(db_index=True)),
                ('refresh_frequency', models.CharField(choices=[('daily', 'daily'), ('weekly', 'weekly'), ('never', 'never')], default='never', max_length=10)),
                ('refresh_time', models.TimeField(null=True)),
                ('endpoint_is_ipif', models.BooleanField(default=False)),
                ('description', models.TextField()),
                ('provider', models.CharField(blank=True, default='', max_length=100)),
                ('repo_active', models.BooleanField(default=False)),
                ('batch_is_canonical', models.BooleanField(default=True)),
                ('rest_write_enabled', models.BooleanField(default=False)),
                ('owners', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('identifier', models.URLField(db_index=True, default='http://noneset.com', editable=False)),
                ('local_id', models.CharField(blank=True, max_length=50)),
                ('label', models.CharField(blank=True, default='', max_length=300)),
                ('createdBy', models.CharField(max_length=300)),
                ('createdWhen', models.DateField()),
                ('modifiedBy', models.CharField(max_length=300)),
                ('modifiedWhen', models.DateField()),
                ('hubIngestedWhen', models.DateTimeField(auto_now_add=True)),
                ('hubModifiedWhen', models.DateTimeField(auto_now=True)),
                ('inputContentHash', models.CharField(default='', max_length=60)),
                ('ipif_repo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ipif_hub.ipifrepo', verbose_name='IPIF Repository')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('uri', models.URLField(db_index=True, primary_key=True, serialize=False)),
                ('label', models.CharField(db_index=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='URI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uri', models.URLField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='Statement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('identifier', models.URLField(db_index=True, default='http://noneset.com', editable=False)),
                ('local_id', models.CharField(blank=True, max_length=50)),
                ('label', models.CharField(blank=True, default='', max_length=300)),
                ('createdBy', models.CharField(max_length=300)),
                ('createdWhen', models.DateField()),
                ('modifiedBy', models.CharField(max_length=300)),
                ('modifiedWhen', models.DateField()),
                ('hubIngestedWhen', models.DateTimeField(auto_now_add=True)),
                ('hubModifiedWhen', models.DateTimeField(auto_now=True)),
                ('inputContentHash', models.CharField(default='', max_length=60)),
                ('statementType_uri', models.URLField(blank=True, db_index=True, null=True)),
                ('statementType_label', models.CharField(blank=True, db_index=True, max_length=300, null=True)),
                ('name', models.CharField(blank=True, db_index=True, max_length=300, null=True)),
                ('role_uri', models.URLField(blank=True, db_index=True, null=True)),
                ('role_label', models.CharField(blank=True, db_index=True, max_length=300, null=True)),
                ('date_sortdate', models.DateField(blank=True, db_index=True, null=True)),
                ('date_label', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('memberOf_uri', models.URLField(blank=True, db_index=True, null=True)),
                ('memberOf_label', models.CharField(blank=True, db_index=True, max_length=300, null=True)),
                ('statementText', models.CharField(blank=True, db_index=True, max_length=1000, null=True)),
                ('ipif_repo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ipif_hub.ipifrepo', verbose_name='IPIF Repository')),
                ('places', models.ManyToManyField(blank=True, to='ipif_hub.Place')),
                ('relatesToPerson', models.ManyToManyField(blank=True, to='ipif_hub.Person', verbose_name='relatedToPerson')),
            ],
            options={
                'abstract': False,
                'unique_together': {('local_id', 'ipif_repo', 'identifier')},
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('identifier', models.URLField(db_index=True, default='http://noneset.com', editable=False)),
                ('local_id', models.CharField(blank=True, max_length=50)),
                ('label', models.CharField(blank=True, default='', max_length=300)),
                ('createdBy', models.CharField(max_length=300)),
                ('createdWhen', models.DateField()),
                ('modifiedBy', models.CharField(max_length=300)),
                ('modifiedWhen', models.DateField()),
                ('hubIngestedWhen', models.DateTimeField(auto_now_add=True)),
                ('hubModifiedWhen', models.DateTimeField(auto_now=True)),
                ('inputContentHash', models.CharField(default='', max_length=60)),
                ('ipif_repo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ipif_hub.ipifrepo', verbose_name='IPIF Repository')),
                ('uris', models.ManyToManyField(blank=True, to='ipif_hub.URI')),
            ],
            options={
                'abstract': False,
                'unique_together': {('local_id', 'ipif_repo', 'identifier')},
            },
        ),
        migrations.AddField(
            model_name='person',
            name='uris',
            field=models.ManyToManyField(blank=True, to='ipif_hub.URI'),
        ),
        migrations.CreateModel(
            name='IngestionJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_complete', models.BooleanField(default=False)),
                ('start_datetime', models.DateTimeField(default=datetime.datetime.now)),
                ('end_datetime', models.DateTimeField(blank=True, default=None, null=True)),
                ('job_type', models.CharField(choices=[('file_batch_upload', 'file batch upload')], max_length=20)),
                ('job_status', models.CharField(default='created', max_length=20)),
                ('job_output', models.TextField(default='')),
                ('ipif_repo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ipif_hub.ipifrepo')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='person',
            unique_together={('local_id', 'ipif_repo', 'identifier')},
        ),
        migrations.CreateModel(
            name='Factoid',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('identifier', models.URLField(db_index=True, default='http://noneset.com', editable=False)),
                ('local_id', models.CharField(blank=True, max_length=50)),
                ('label', models.CharField(blank=True, default='', max_length=300)),
                ('createdBy', models.CharField(max_length=300)),
                ('createdWhen', models.DateField()),
                ('modifiedBy', models.CharField(max_length=300)),
                ('modifiedWhen', models.DateField()),
                ('hubIngestedWhen', models.DateTimeField(auto_now_add=True)),
                ('hubModifiedWhen', models.DateTimeField(auto_now=True)),
                ('inputContentHash', models.CharField(default='', max_length=60)),
                ('ipif_repo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ipif_hub.ipifrepo', verbose_name='IPIF Repository')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factoids', related_query_name='factoids', to='ipif_hub.person')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factoids', related_query_name='factoids', to='ipif_hub.source')),
                ('statement', models.ManyToManyField(related_name='factoids', related_query_name='factoids', to='ipif_hub.Statement', verbose_name='statements')),
            ],
            options={
                'abstract': False,
                'unique_together': {('local_id', 'ipif_repo', 'identifier')},
            },
        ),
    ]
