# Generated by Django 3.2.12 on 2022-03-30 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipif_hub', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factoid',
            name='id',
            field=models.URLField(default='http://noneset.com', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='factoid',
            name='local_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='ipifrepo',
            name='refresh_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='person',
            name='id',
            field=models.URLField(default='http://noneset.com', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='person',
            name='local_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='source',
            name='id',
            field=models.URLField(default='http://noneset.com', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='source',
            name='local_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='statement',
            name='id',
            field=models.URLField(default='http://noneset.com', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='statement',
            name='local_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='factoid',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='person',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='source',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='statement',
            unique_together=set(),
        ),
    ]
