# Generated by Django 3.2.12 on 2022-03-30 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ipif_hub', '0002_auto_20220330_1025'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='factoid',
            unique_together={('local_id', 'ipif_repo')},
        ),
        migrations.AlterUniqueTogether(
            name='person',
            unique_together={('local_id', 'ipif_repo')},
        ),
        migrations.AlterUniqueTogether(
            name='source',
            unique_together={('local_id', 'ipif_repo')},
        ),
        migrations.AlterUniqueTogether(
            name='statement',
            unique_together={('local_id', 'ipif_repo')},
        ),
        migrations.RemoveField(
            model_name='factoid',
            name='pre_serialized',
        ),
        migrations.RemoveField(
            model_name='person',
            name='pre_serialized',
        ),
        migrations.RemoveField(
            model_name='source',
            name='pre_serialized',
        ),
        migrations.RemoveField(
            model_name='statement',
            name='pre_serialized',
        ),
    ]
