# Generated by Django 3.2.12 on 2022-03-19 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipif_hub', '0002_person_pre_serialized'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='pre_serialized',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
