# Generated by Django 3.2.12 on 2022-03-19 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipif_hub', '0003_alter_person_pre_serialized'),
    ]

    operations = [
        migrations.AddField(
            model_name='factoid',
            name='pre_serialized',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='source',
            name='pre_serialized',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='statement',
            name='pre_serialized',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
