# Generated by Django 3.2.12 on 2022-03-30 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipif_hub', '0003_auto_20220330_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factoid',
            name='id',
            field=models.URLField(db_index=True, default='http://noneset.com', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ipifrepo',
            name='endpoint_slug',
            field=models.CharField(db_index=True, max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ipifrepo',
            name='endpoint_url',
            field=models.URLField(db_index=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='id',
            field=models.URLField(db_index=True, default='http://noneset.com', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='place',
            name='label',
            field=models.CharField(db_index=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='uri',
            field=models.URLField(db_index=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='source',
            name='id',
            field=models.URLField(db_index=True, default='http://noneset.com', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='statement',
            name='date_label',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='statement',
            name='date_sortdate',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='statement',
            name='id',
            field=models.URLField(db_index=True, default='http://noneset.com', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='statement',
            name='memberOf_label',
            field=models.CharField(blank=True, db_index=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='statement',
            name='memberOf_uri',
            field=models.URLField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='statement',
            name='name',
            field=models.CharField(blank=True, db_index=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='statement',
            name='role_label',
            field=models.CharField(blank=True, db_index=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='statement',
            name='role_uri',
            field=models.URLField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='statement',
            name='statementText',
            field=models.CharField(blank=True, db_index=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='statement',
            name='statementType_label',
            field=models.CharField(blank=True, db_index=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='statement',
            name='statementType_uri',
            field=models.URLField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='uri',
            name='uri',
            field=models.URLField(db_index=True),
        ),
    ]
