# Generated by Django 3.2.12 on 2022-03-23 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipif_hub', '0004_auto_20220319_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factoid',
            name='statement',
            field=models.ManyToManyField(related_name='factoids', related_query_name='factoids', to='ipif_hub.Statement', verbose_name='statements'),
        ),
    ]
