# Generated by Django 3.2.12 on 2022-06-15 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipif_hub', '0004_auto_20220330_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipifrepo',
            name='ids_are_local',
            field=models.BooleanField(default=True),
        ),
    ]
