# Generated by Django 3.2.12 on 2022-06-15 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipif_hub', '0005_ipifrepo_ids_are_local'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipifrepo',
            name='endpoint_name',
            field=models.CharField(default='', max_length=30),
        ),
    ]
