# Generated by Django 3.2.12 on 2022-03-29 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipif_hub', '0005_alter_factoid_statement'),
    ]

    operations = [
        migrations.AddField(
            model_name='factoid',
            name='label',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='statement',
            name='label',
            field=models.CharField(default='', max_length=300),
        ),
    ]
