# Generated by Django 3.2.12 on 2022-06-15 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ipif_hub', '0006_ipifrepo_endpoint_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ipifrepo',
            old_name='endpoint_url',
            new_name='endpoint_uri',
        ),
    ]
