# Generated by Django 3.2.12 on 2022-06-15 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipif_hub', '0008_remove_ipifrepo_ids_are_local'),
    ]

    operations = [
        migrations.AddField(
            model_name='factoid',
            name='inputContentHash',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='person',
            name='inputContentHash',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='source',
            name='inputContentHash',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='statement',
            name='inputContentHash',
            field=models.CharField(default='', max_length=30),
        ),
    ]
