# Generated by Django 3.2.12 on 2022-06-22 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipif_hub', '0009_auto_20220615_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factoid',
            name='inputContentHash',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='factoid',
            name='label',
            field=models.CharField(default='', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='ipifrepo',
            name='refresh_frequency',
            field=models.CharField(choices=[('daily', 'daily'), ('weekly', 'weekly'), ('never', 'never')], max_length=10),
        ),
        migrations.AlterField(
            model_name='person',
            name='inputContentHash',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='person',
            name='label',
            field=models.CharField(default='', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='inputContentHash',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='source',
            name='label',
            field=models.CharField(default='', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='statement',
            name='inputContentHash',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='statement',
            name='label',
            field=models.CharField(default='', max_length=300, null=True),
        ),
    ]
