# Generated by Django 3.2.12 on 2022-06-22 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipif_hub', '0010_auto_20220622_0818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factoid',
            name='label',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='person',
            name='label',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='source',
            name='label',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='statement',
            name='label',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
    ]
