# Generated by Django 3.2.12 on 2022-06-23 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipif_hub', '0011_auto_20220622_0821'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipifrepo',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='ipifrepo',
            name='password',
            field=models.CharField(default='password', max_length=128, verbose_name='password'),
            preserve_default=False,
        ),
    ]
