# Generated by Django 3.2.12 on 2022-06-29 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipif_hub', '0012_auto_20220623_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipifrepo',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ipifrepo',
            name='provider',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
