# Generated by Django 3.2.12 on 2022-06-29 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipif_hub', '0014_auto_20220629_0918'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipifrepo',
            name='email_validated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ipifrepo',
            name='repo_active',
            field=models.BooleanField(default=False),
        ),
    ]
