# Generated by Django 3.2.12 on 2022-06-29 11:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ipif_hub', '0015_auto_20220629_0954'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ipifrepo',
            name='email_validated',
        ),
        migrations.RemoveField(
            model_name='ipifrepo',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='ipifrepo',
            name='password',
        ),
        migrations.RemoveField(
            model_name='ipifrepo',
            name='primary_email',
        ),
        migrations.RemoveField(
            model_name='ipifrepo',
            name='secondary_email',
        ),
        migrations.RemoveField(
            model_name='ipifrepo',
            name='tertiary_email',
        ),
        migrations.AddField(
            model_name='ipifrepo',
            name='owners',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
