# Generated by Django 3.2.12 on 2022-08-05 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipif_hub', '0019_alter_ingestionjob_start_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingestionjob',
            name='id',
            field=models.UUIDField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
