# Generated by Django 3.2.12 on 2022-08-05 10:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ipif_hub', '0020_alter_ingestionjob_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingestionjob',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ingestionjob',
            name='job_type',
            field=models.CharField(choices=[('file_batch_upload', 'file batch upload')], max_length=20),
        ),
    ]
