# Generated by Django 3.2.12 on 2022-08-05 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ipif_hub', '0021_auto_20220805_1010'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingestionjob',
            old_name='complete',
            new_name='is_complete',
        ),
    ]
