# Generated by Django 3.2.12 on 2022-08-08 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipif_hub', '0023_auto_20220805_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingestionjob',
            name='job_status',
            field=models.CharField(default='created', max_length=20),
        ),
    ]
