# Generated by Django 3.2.12 on 2022-08-08 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipif_hub', '0025_alter_ipifrepo_endpoint_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipifrepo',
            name='refresh_frequency',
            field=models.CharField(choices=[('daily', 'daily'), ('weekly', 'weekly'), ('never', 'never')], default='never', max_length=10),
        ),
        migrations.AlterField(
            model_name='ipifrepo',
            name='refresh_time',
            field=models.TimeField(null=True),
        ),
    ]
