# Generated by Django 3.2.12 on 2022-08-08 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipif_hub', '0026_auto_20220808_0846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipifrepo',
            name='endpoint_is_ipif',
            field=models.BooleanField(default=False),
        ),
    ]
