# Generated by Django 3.2.12 on 2022-08-08 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipif_hub', '0028_alter_ipifrepo_endpoint_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipifrepo',
            name='endpoint_slug',
            field=models.CharField(db_index=True, editable=False, max_length=20, primary_key=True, serialize=False),
        ),
    ]
